from __future__ import annotations

import io
import os
import ssl
import statistics
import sys
import traceback
from shutil import which
from typing import Callable, Optional

import cv2
import numpy as np
import paddle
from PIL import Image
from pdf2image import convert_from_path
from paddleocr import PaddleOCR
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pptx.enum.text import MSO_ANCHOR, MSO_AUTO_SIZE
from pptx.util import Inches, Pt

try:
    import torch
    TORCH_IMPORT_ERROR = None
except Exception as exc:
    torch = None
    TORCH_IMPORT_ERROR = exc

ssl._create_default_https_context = ssl._create_unverified_context
os.environ["FLAGS_use_mkldnn"] = "0"
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

POPPLER_PATH = None
SCAN_DPI = 200
ENABLE_LAMA = os.environ.get("CONVERTPPT_USE_LAMA", "").strip().lower() in {"1", "true", "yes", "on"}
SUPPORTED_EXTENSIONS = {".pdf", ".ppt", ".pptx"}
WATERMARK_KEYWORDS = [
    "notebooklm",
    "generated by",
    "google",
    "overview",
    "briefing",
    "audio",
    "summary",
    "ai overview",
    "source guide",
    "listening",
]
FORCED_ERASE_REGIONS = [
    [0.70, 0.88, 1.0, 1.0],
]
STANDARD_SIZES = [
    5,
    6,
    7,
    8,
    9,
    10,
    10.5,
    11,
    12,
    13,
    14,
    15,
    16,
    18,
    20,
    22,
    24,
    26,
    28,
    32,
    36,
    40,
]
DEFAULT_OCR_CONFIG = {
    "lang": "ch",
    "use_angle_cls": True,
    "enable_mkldnn": False,
    "use_mp": False,
    "show_log": False,
    "det_limit_side_len": 2500,
    "det_db_thresh": 0.08,
    "det_db_box_thresh": 0.2,
    "det_db_unclip_ratio": 2.5,
    "use_dilation": True,
}

LogFn = Callable[[str], None]

_DEVICE = "cuda" if torch is not None and torch.cuda.is_available() else "cpu"
_RUNTIME_READY = False
_LAMA_MODEL = None
_HAS_LAMA = False


def _log(logger: Optional[LogFn], message: str) -> None:
    if logger is None:
        return
    logger(str(message))


def get_runtime_summary() -> list[str]:
    conda_prefix = os.environ.get("CONDA_PREFIX") or sys.prefix
    conda_default_env = os.environ.get("CONDA_DEFAULT_ENV") or "base/unknown"
    repair_backend = "LaMa" if ENABLE_LAMA else "OpenCV"
    return [
        f"Python: {sys.executable}",
        f"Conda env: {conda_default_env}",
        f"Conda prefix: {conda_prefix}",
        f"Repair backend: {repair_backend}",
    ]


def log_runtime_summary(logger: Optional[LogFn] = print) -> None:
    for line in get_runtime_summary():
        _log(logger, line)


def _patch_torch_load_for_cpu() -> None:
    if torch is None:
        return
    if _DEVICE != "cpu":
        return
    if getattr(torch.jit.load, "_convertppt_safe_cpu_patch", False):
        return

    original_load = torch.jit.load

    def _safe_cpu_load(f, map_location=None, _extra_files=None):
        return original_load(
            f,
            map_location=torch.device("cpu"),
            _extra_files=_extra_files,
        )

    _safe_cpu_load._convertppt_safe_cpu_patch = True
    torch.jit.load = _safe_cpu_load


def initialize_runtime(logger: Optional[LogFn] = print) -> None:
    global _HAS_LAMA, _LAMA_MODEL, _RUNTIME_READY

    log_runtime_summary(logger)
    if _RUNTIME_READY:
        return

    if not ENABLE_LAMA:
        _HAS_LAMA = False
        _LAMA_MODEL = None
        _RUNTIME_READY = True
        _log(logger, "Current Anaconda mode uses OpenCV repair by default.")
        _log(logger, "Set CONVERTPPT_USE_LAMA=1 if you later repair the Torch environment.")
        return

    _log(logger, f"AI inpainting backend: {_DEVICE.upper()}")
    if TORCH_IMPORT_ERROR is not None:
        _log(logger, f"Torch unavailable, using OpenCV fallback: {TORCH_IMPORT_ERROR}")

    _patch_torch_load_for_cpu()

    try:
        from simple_lama_inpainting import SimpleLama

        _LAMA_MODEL = SimpleLama()
        _HAS_LAMA = True
        _log(logger, "LaMa model loaded successfully.")
    except Exception as exc:
        _HAS_LAMA = False
        _LAMA_MODEL = None
        _log(logger, f"LaMa unavailable, using OpenCV fallback: {exc}")

    _RUNTIME_READY = True


def resolve_poppler_path() -> Optional[str]:
    if POPPLER_PATH:
        return POPPLER_PATH
    if which("pdftoppm"):
        return None

    candidate_dirs = [
        os.environ.get("POPPLER_PATH"),
        os.path.join(os.getcwd(), "poppler", "Library", "bin"),
        os.path.join(os.getcwd(), "poppler", "bin"),
    ]
    for candidate in candidate_dirs:
        if candidate and os.path.exists(os.path.join(candidate, "pdftoppm.exe")):
            return candidate
    return None


def create_ocr_engine(logger: Optional[LogFn] = print) -> PaddleOCR:
    initialize_runtime(logger)
    _log(logger, "Initializing OCR engine (CPU stable mode)...")
    paddle.set_device("cpu")
    ocr_engine = PaddleOCR(**DEFAULT_OCR_CONFIG)
    _log(logger, "OCR engine is ready.")
    return ocr_engine


def is_supported_input(path: str) -> bool:
    return os.path.splitext(path)[1].lower() in SUPPORTED_EXTENSIONS


def build_output_path(input_path: str, suffix: str = "_AI_REPAIRED") -> str:
    base, _ = os.path.splitext(input_path)
    return f"{base}{suffix}.pptx"


def px_to_inches(px: float, dpi: int = 72) -> float:
    return px / dpi


def is_mostly_english(text: str) -> bool:
    if not text:
        return False
    ascii_count = sum(1 for char in text if char.isascii())
    return (ascii_count / len(text)) > 0.7


def snap_to_standard_size(size: float) -> float:
    return min(STANDARD_SIZES, key=lambda candidate: abs(candidate - size))


def normalize_image(pil_image: Image.Image) -> Image.Image:
    if pil_image.mode == "RGB":
        return pil_image
    return pil_image.convert("RGB")


def convert_raw_to_blocks(ocr_data):
    if not ocr_data:
        return []

    blocks = []
    for line in ocr_data:
        box = line[0]
        text = line[1][0]
        height = box[2][1] - box[0][1]
        width = box[2][0] - box[0][0]
        blocks.append(
            {
                "lines": [text],
                "box": box,
                "avg_height": height,
                "line_widths": [width],
                "sample_box": box,
                "polygons": [box],
            }
        )
    return blocks


def smart_clean_image_ai(
    pil_img: Image.Image,
    blocks_to_clean,
    logger: Optional[LogFn] = print,
) -> Image.Image:
    try:
        initialize_runtime(logger)
        pil_img = normalize_image(pil_img)
        width, height = pil_img.size
        mask = np.zeros((height, width), dtype=np.uint8)

        for block in blocks_to_clean:
            for polygon in block["polygons"]:
                points = np.array(polygon, dtype=np.int32)
                cv2.fillPoly(mask, [points], 255)

        for region in FORCED_ERASE_REGIONS:
            x1 = int(region[0] * width)
            y1 = int(region[1] * height)
            x2 = int(region[2] * width)
            y2 = int(region[3] * height)
            cv2.rectangle(mask, (x1, y1), (x2, y2), 255, -1)

        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (15, 15))
        mask = cv2.dilate(mask, kernel, iterations=1)
        feathered_mask = cv2.GaussianBlur(mask, (21, 21), 11)

        if _HAS_LAMA and _LAMA_MODEL is not None:
            try:
                return _LAMA_MODEL(pil_img, Image.fromarray(feathered_mask))
            except RuntimeError:
                if torch is not None and torch.cuda.is_available():
                    torch.cuda.empty_cache()

        img_np = cv2.cvtColor(np.array(pil_img), cv2.COLOR_RGB2BGR)
        repaired = cv2.inpaint(img_np, mask, 5, cv2.INPAINT_TELEA)
        return Image.fromarray(cv2.cvtColor(repaired, cv2.COLOR_BGR2RGB))
    except Exception as exc:
        _log(logger, f"Image cleanup failed, keeping original image: {exc}")
        return normalize_image(pil_img)


def get_text_color_kmeans(pil_image: Image.Image, box) -> RGBColor:
    try:
        pil_image = normalize_image(pil_image)
        roi = np.array(pil_image)[
            int(max(0, box[0][1])) : int(min(pil_image.size[1], box[2][1])),
            int(max(0, box[0][0])) : int(min(pil_image.size[0], box[2][0])),
        ]
        if roi.size == 0:
            return RGBColor(0, 0, 0)

        pixels = roi.reshape((-1, 3)).astype(np.float32)
        _, labels, centers = cv2.kmeans(
            pixels,
            2,
            None,
            (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0),
            10,
            cv2.KMEANS_RANDOM_CENTERS,
        )
        _, counts = np.unique(labels, return_counts=True)
        indices = np.argsort(counts)[::-1]
        background_color = centers[indices[0]]
        foreground_color = centers[indices[1]] if len(indices) > 1 else background_color

        def get_luminance(color) -> float:
            return 0.299 * color[0] + 0.587 * color[1] + 0.114 * color[2]

        background_luminance = get_luminance(background_color)
        foreground_luminance = get_luminance(foreground_color)
        if background_luminance > 200:
            final_color = (
                foreground_color
                if foreground_luminance < background_luminance
                else background_color
            )
        elif background_luminance < 50:
            final_color = (
                foreground_color
                if foreground_luminance > background_luminance
                else background_color
            )
        else:
            final_color = foreground_color

        if get_luminance(final_color) > 230:
            return RGBColor(0, 0, 0)
        return RGBColor(
            int(final_color[0]),
            int(final_color[1]),
            int(final_color[2]),
        )
    except Exception:
        return RGBColor(0, 0, 0)


def process_single_image_content(
    pil_img: Image.Image,
    ocr_engine: PaddleOCR,
    logger: Optional[LogFn] = print,
):
    try:
        pil_img = normalize_image(pil_img)
        result = ocr_engine.ocr(np.array(pil_img), cls=True)

        if result is None or len(result) == 0 or result[0] is None:
            _log(logger, "OCR returned empty result, retrying with 80% scaled image...")
            width, height = pil_img.size
            small_img = pil_img.resize((int(width * 0.8), int(height * 0.8)), Image.LANCZOS)
            retry_result = ocr_engine.ocr(np.array(small_img), cls=True)

            if retry_result and len(retry_result) > 0 and retry_result[0]:
                _log(logger, f"OCR retry succeeded with {len(retry_result[0])} text blocks.")
                scale_recover = 1.0 / 0.8
                restored_data = []
                for line in retry_result[0]:
                    box = np.array(line[0]) * scale_recover
                    restored_data.append([box.tolist(), line[1]])
                result = [restored_data]
            else:
                _log(logger, "OCR retry still returned empty result; only background will be kept.")
                return None, []

        text_data = []
        for line in result[0]:
            if not line or len(line) < 2:
                continue

            text_content = line[1][0]
            if not isinstance(text_content, str):
                continue

            is_watermark = any(keyword in text_content.lower() for keyword in WATERMARK_KEYWORDS)
            if len(text_content) < 2 and not text_content.isdigit() and not text_content.isalpha():
                is_watermark = True

            if not is_watermark:
                text_data.append(line)

        merged_blocks = convert_raw_to_blocks(text_data)
        clean_bg = smart_clean_image_ai(pil_img, merged_blocks, logger=logger)
        return clean_bg, merged_blocks
    except Exception as exc:
        _log(logger, f"OCR processing failed: {exc}")
        return None, []


def calculate_unified_font_sizes(blocks, scale_y: float):
    if not blocks:
        return []

    raw_sizes = []
    for block in blocks:
        text = block["lines"][0]
        box_height_px = block["avg_height"]
        physical_height_pt = (box_height_px * scale_y) * (72 / SCAN_DPI)
        fill_ratio = 0.50 if is_mostly_english(text) else 0.55
        calculated_size = physical_height_pt * fill_ratio
        block["temp_size"] = calculated_size
        raw_sizes.append(calculated_size)

    if not raw_sizes:
        return blocks

    median_size = statistics.median(raw_sizes)
    for block in blocks:
        current_size = block["temp_size"]
        final_size = median_size if 0.8 * median_size <= current_size <= 1.2 * median_size else current_size
        text = block["lines"][0]
        block["final_font_pt"] = snap_to_standard_size(final_size)
        block["font_name"] = "Arial" if is_mostly_english(text) else "Microsoft YaHei"

    return blocks


def create_text_boxes_on_slide(
    slide,
    merged_blocks,
    original_img: Image.Image,
    prs: Presentation,
    offset_x=0,
    offset_y=0,
    scale_x: float = 1.0,
    scale_y: float = 1.0,
) -> None:
    prs_width_inches = prs.slide_width.inches
    off_x_val = offset_x.inches if hasattr(offset_x, "inches") else 0
    blocks_with_font = calculate_unified_font_sizes(merged_blocks, scale_y)

    for block in blocks_with_font:
        box = block["box"]
        full_text = block["lines"][0]

        left_inch = px_to_inches(box[0][0] * scale_x, SCAN_DPI)
        top_inch = px_to_inches(box[0][1] * scale_y, SCAN_DPI)

        box_width_px = box[2][0] - box[0][0]
        box_height_px = box[2][1] - box[0][1]
        width_inch = px_to_inches(box_width_px * scale_x, SCAN_DPI) * 1.05
        height_inch = px_to_inches(box_height_px * scale_y, SCAN_DPI)

        if off_x_val + left_inch + width_inch > prs_width_inches:
            width_inch = prs_width_inches - (off_x_val + left_inch) - 0.1

        if width_inch <= 0 or height_inch <= 0:
            continue

        tx_box = slide.shapes.add_textbox(
            offset_x + Inches(left_inch),
            offset_y + Inches(top_inch),
            Inches(width_inch),
            Inches(height_inch),
        )
        text_frame = tx_box.text_frame
        text_frame.word_wrap = False
        text_frame.auto_size = MSO_AUTO_SIZE.NONE
        text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE
        text_frame.margin_left = 0
        text_frame.margin_right = 0
        text_frame.margin_top = 0
        text_frame.margin_bottom = 0

        paragraph = text_frame.paragraphs[0]
        paragraph.text = full_text
        paragraph.font.size = Pt(max(5, block["final_font_pt"]))
        paragraph.font.name = block["font_name"]
        paragraph.font.color.rgb = get_text_color_kmeans(original_img, block["sample_box"])
        paragraph.line_spacing = 1.0


def iter_picture_shapes(shapes, parent_offset=(0, 0)):
    for shape in shapes:
        left = parent_offset[0] + shape.left
        top = parent_offset[1] + shape.top
        if shape.shape_type == MSO_SHAPE_TYPE.GROUP:
            yield from iter_picture_shapes(shape.shapes, (left, top))
        elif shape.shape_type in [MSO_SHAPE_TYPE.PICTURE, MSO_SHAPE_TYPE.PLACEHOLDER] and hasattr(shape, "image"):
            yield shape, left, top


def process_pdf_file(
    pdf_path: str,
    output_ppt_path: str,
    ocr_engine: PaddleOCR,
    logger: Optional[LogFn] = print,
) -> str:
    _log(logger, "Running PDF conversion...")
    poppler_path = resolve_poppler_path()
    if poppler_path is None and not which("pdftoppm"):
        raise RuntimeError(
            "PDF conversion requires Poppler. Please install Poppler or set POPPLER_PATH."
        )
    try:
        images = convert_from_path(pdf_path, dpi=SCAN_DPI, poppler_path=poppler_path)
    except Exception as exc:
        raise RuntimeError(f"Failed to read PDF: {exc}") from exc

    prs = Presentation()
    if images:
        first_image = normalize_image(images[0])
        prs.slide_width = Inches(px_to_inches(first_image.width, SCAN_DPI))
        prs.slide_height = Inches(px_to_inches(first_image.height, SCAN_DPI))

    for index, image in enumerate(images, start=1):
        _log(logger, f"Processing PDF page {index}/{len(images)}...")
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        try:
            image = normalize_image(image)
            clean_bg, blocks = process_single_image_content(image, ocr_engine, logger=logger)
            final_bg = clean_bg if clean_bg is not None else image
            bg_stream = io.BytesIO()
            final_bg.save(bg_stream, format="JPEG")
            bg_stream.seek(0)
            slide.shapes.add_picture(bg_stream, 0, 0, width=prs.slide_width, height=prs.slide_height)
            if blocks:
                create_text_boxes_on_slide(slide, blocks, image, prs)
            else:
                _log(logger, "No text blocks found on this page; keeping cleaned background only.")
        except Exception as exc:
            _log(logger, f"Page {index} failed: {exc}")
            traceback.print_exc()

    prs.save(output_ppt_path)
    _log(logger, f"Saved output to: {output_ppt_path}")
    return output_ppt_path


def process_pptx_file(
    input_pptx: str,
    output_pptx: str,
    ocr_engine: PaddleOCR,
    logger: Optional[LogFn] = print,
) -> str:
    _log(logger, "Running PPTX conversion...")
    prs = Presentation(input_pptx)

    for slide_index, slide in enumerate(prs.slides, start=1):
        _log(logger, f"Processing slide {slide_index}/{len(prs.slides)}...")
        for shape, left, top in list(iter_picture_shapes(slide.shapes)):
            try:
                img_pil = normalize_image(Image.open(io.BytesIO(shape.image.blob)))
                clean_bg, blocks = process_single_image_content(img_pil, ocr_engine, logger=logger)
                final_bg = clean_bg if clean_bg is not None else img_pil

                bg_stream = io.BytesIO()
                final_bg.save(bg_stream, format="PNG")
                bg_stream.seek(0)
                slide.shapes.add_picture(bg_stream, left, top, shape.width, shape.height)

                if blocks:
                    create_text_boxes_on_slide(
                        slide,
                        blocks,
                        img_pil,
                        prs,
                        offset_x=left,
                        offset_y=top,
                        scale_x=shape.width.inches / px_to_inches(img_pil.width, SCAN_DPI),
                        scale_y=shape.height.inches / px_to_inches(img_pil.height, SCAN_DPI),
                    )

                shape.left = Inches(-20)
            except Exception as exc:
                _log(logger, f"Embedded image conversion failed: {exc}")

    prs.save(output_pptx)
    _log(logger, f"Saved output to: {output_pptx}")
    return output_pptx


def convert_file(
    input_file: str,
    output_file: Optional[str] = None,
    ocr_engine: Optional[PaddleOCR] = None,
    logger: Optional[LogFn] = print,
) -> str:
    if not os.path.exists(input_file):
        raise FileNotFoundError(f"Input file not found: {input_file}")

    extension = os.path.splitext(input_file)[1].lower()
    if extension not in SUPPORTED_EXTENSIONS:
        raise ValueError(f"Unsupported file type: {extension}")

    if output_file is None:
        output_file = build_output_path(input_file)

    engine = ocr_engine or create_ocr_engine(logger)
    if extension == ".pdf":
        return process_pdf_file(input_file, output_file, engine, logger=logger)
    return process_pptx_file(input_file, output_file, engine, logger=logger)
